<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/12/15 20:32:53

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
